
server:
  port: 1003
spring:
  profiles:
    active: home
ldb:
  mqtt:
    url: ws://10.20.255.225:8083/mqtt
    topic:
      supply: supply
bean:
  cl: hehel
  name: sdsdsds
mybatis-plus:
  configuration:
    log-impl: com.black.core.log.IbatisLog
chief:
  enabled-visit-database: true
sql:
  mapperPaths: xml-sql/
  open-servlet: true
  other:
    one:
      mapperPaths: xml-sql/
      environment:
        auto-set-id: false
    two:
      mapperPaths: xml-sql/,iu
ftl:
  paths: xml-sql/
  nullDefaultValue: 无数据
mapping:
  df = is_deleted = false
