
server:
  port: 1003
spring:
  profiles:
    active: prod
ldb:
  mqtt:
    url: ws://10.20.255.225:8083/mqtt
    topic:
      supply: supply
bean:
  cl: hehel
  name: sdsdsds
mybatis-plus:
  configuration:
    log-impl: com.black.core.log.IbatisLog
