
server:
  port: 1003
spring:
  profiles:
    active: prod
ldb:
  mqtt:
    url: ws://10.20.255.225:8083/mqtt
    topic:
      supply: supply
bean:
  cl: hehel
  name: sdsdsds
mybatis-plus:
  configuration:
    log-impl: com.black.core.log.IbatisLog
chief:
  enabled-visit-database: true
sql:
  config:
    one:
      mapperPaths: xml-sql/
      environment:
        auto-set-id: false
    master_v2:
      mapperPaths: xml-sql/,iu
mapping:
  df = is_deleted = false
